version: "3"

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
    - var/run/docker.sock:/var/run/docker.sock
    - ${CONFIG}/portainer/data:data
    - ${CONFIG}/portainer/shared:shared
    environment:
      - TZ=${TZ}
    restart: always