version: "3"

# Setup enviroment variables: ${TZ} ${CONFIG} ${PUID} ${PGID} ${ROOT}
# Take a look at the README.md for help
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
    - var/run/docker.sock:/var/run/docker.sock
    - ${CONFIG}/portainer/data:data
    - ${CONFIG}/portainer/shared:shared
    environment:
      - TZ=${TZ}
    restart: always